import { createElement } from 'lwc';
import IDS_FormBased_editform from 'c/iDS_FormBased_editform';

describe('c-i-d-s-form-based-editform', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-i-d-s-form-based-editform', {
            is: IDS_FormBased_editform
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});